# Generated by Django 4.1.3 on 2022-11-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_inquiry',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
