# Generated by Django 4.1.3 on 2022-11-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0002_book_current_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='scenario_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
