# Generated by Django 4.1.3 on 2022-11-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0003_book_scenario_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
