# Generated by Django 4.1.3 on 2022-11-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0004_book_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='empty_placeholder',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
