# Generated by Django 4.1.3 on 2023-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0006_remove_book_current_inquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.TextField(),
        ),
    ]
