# Generated by Django 4.1.3 on 2023-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0007_alter_book_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='next_scenario',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='chat_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
