# Generated by Django 4.1.3 on 2023-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0008_book_next_scenario_alter_book_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_chat_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
