# Generated by Django 4.1.3 on 2023-02-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0009_book_full_chat_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cave', models.TextField(choices=[('GREEN', 'GREEN'), ('BEAUTY', 'BEAUTY'), ('RAGE', 'RAGE'), ('BODY', 'BODY'), ('FAITH', 'FAITH'), ('KNOWLEDGE', 'KNOWLEDGE'), ('DISORDER', 'DISORDER')], default='GREEN')),
                ('interactions_available', models.IntegerField(default='0')),
                ('next_scenario', models.IntegerField(default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='next_scenario',
        ),
    ]
