# Generated by Django 4.1.3 on 2023-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0011_user_book_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hope', models.TextField(blank=True, default='')),
                ('fear', models.TextField(blank=True, default='')),
            ],
        ),
    ]
